// <auto-generated />
using System;
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Computer Programming"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Amazon City",
                            Name = "Amazon",
                            PhoneNumber = "897-516-7895",
                            PostalCode = "1244",
                            State = "CA",
                            StreetAddress = "Online"
                        },
                        new
                        {
                            Id = 2,
                            City = "Tech City",
                            Name = "Tech Solution",
                            PhoneNumber = "727-916-8713",
                            PostalCode = "5484",
                            State = "IL",
                            StreetAddress = "124 Tech Street"
                        });
                });

            modelBuilder.Entity("Bulky.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Bulky.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mark Reed",
                            CategoryId = 1,
                            Description = "C# & C++: 5 Books in 1 aims to make it simple for you to begin your journey, regardless of your skills or expertise. With step-by-step instructions, this guide will have you writing code in 2 programming languages, in no time.\r\n\r\n1. You will discover a gradual, beginner-friendly progress and learn the basics of C# and C++ in no time.\r\n\r\n2. You will study theory and how to put it into practice RIGHT NOW.\r\n\r\n3. You will not only find a boring instruction manual but also a dynamic and interactive guide that offers solid PRACTICAL experience.\r\n\r\n4. All the ESSENTIAL TOOLS and best strategies to learn coding for complete beginners + advanced knowledge for those with more experience.\r\n\r\n5. You will learn the RIGHT SKILLS for REAL APPLICATIONS with easy-to-understand exercises and examples.\r\n",
                            ISBN = "979-8390090077",
                            ListPrice = 30.0,
                            Price = 25.0,
                            Price100 = 30.0,
                            Price50 = 20.0,
                            Title = "C# & C++"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Philip Robbins",
                            CategoryId = 2,
                            Description = "An overview of Python, its history, and its key uses to demonstrate its potential and how understanding it may help you.\r\n    How to install Python and pick the best distribution on Windows or Mac, including the best IDE, to get started.\r\n    Object-Oriented Programming (OOP) and why you must know it, including objects, methods, and inheritance, taught logically and progressively to enable you utilize this user-friendly language and its basic syntax rapidly.\r\n    Chapters include actual codes and activities to test your abilities.\r\n    The greatest Python programming strategies to optimize script performance, including a whole section\r\n    For a 360-degree perspective of complex programming and easy entry, use Github, pip, Virtual Environment, and Unit Testing.\r\n    The exercise solutions (but only after you've tried them yourself)\r\n    Scan the QR code within the book for a bonus Python Interview Questions and Answers.lot more!",
                            ISBN = "979-8376161821",
                            ListPrice = 33.0,
                            Price = 15.0,
                            Price100 = 30.0,
                            Price50 = 10.0,
                            Title = "Python Programming"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Chris Minnick",
                            CategoryId = 3,
                            Description = "JavaScript in One For Dummies saves shelf space by providing a full introduction to JavaScript and its real-world applications. This book covers JavaScript foundations before covering libraries, frameworks, and runtime environments for beginners and experts. Anyone can learn JavaScript basics, even if they've never coded. Then discuss React.js, Vue.js, Svelte, and Node.js, today's top frameworks. Get comfy and learn JavaScript!",
                            ISBN = "978-1119906834",
                            ListPrice = 10.0,
                            Price = 1.0,
                            Price100 = 10.0,
                            Price50 = 7.0,
                            Title = "JavaScript All-in-One For Dummies 1st Edition"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Neuronwaves",
                            CategoryId = 2,
                            Description = "In this fast-paced environment, we must develop crucial skills for success. In an age of fake news, social media, and information overload, critical thinking, reasoning, and problem-solving are essential.\r\nIn our daily lives, critical thinking, logic, and problem-solving help us think clearly and make good judgments. These talents help us understand why things are the way they are, the forces and circumstances at play, and how to change them.",
                            ISBN = " 979-8866530397 ",
                            ListPrice = 28.0,
                            Price = 20.0,
                            Price100 = 20.0,
                            Price50 = 15.0,
                            Title = "Critical Thinking, Logic & Problem Solving"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Casey Hardman",
                            CategoryId = 4,
                            Description = "This guide teaches novices in game creation and programming the basics of Unity, C#, and object-oriented programming. New ideas are explained and shown.\r\nFrom an introduction to Unity, you'll learn about scenes, GameObjects, prefabs, components, and engine windows. After examining syntax rules, formatting, methods, variables, objects and types, classes, and inheritance, you'll write and test code. The book later covers Unity's serialization system and Inspector script data exposure. ",
                            ISBN = " 978-1484256558",
                            ListPrice = 59.0,
                            Price = 40.0,
                            Price100 = 20.0,
                            Price50 = 30.0,
                            Title = "Game Programming with Unity and C#: A Complete Beginner’s Guide"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Walter Shields",
                            CategoryId = 3,
                            Description = "Any database administration specialist would tell you that SQL is the most popular and trustworthy data management language, with no indications of slowing. Walter Shields, a mentor and SQL specialist, simplifies relational database management in this thorough tutorial.\r\n\r\nSQL QuickStart Guide is perfect for people wishing to further their careers, developers looking to improve their skills, or anybody who wants to participate in our data-driven future—even without coding expertise!",
                            ISBN = " 978-1945051234",
                            ListPrice = 25.0,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "SQL QuickStart Guide"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Stanley  Lippman",
                            CategoryId = 5,
                            Description = "C++ Primer, Fifth Edition, introduces the C++ standard library from the outset, drawing on its common functions and facilities to help you write useful programs without first having to master every language detail. The book’s many examples have been revised to use the new language features and demonstrate how to make the best use of them. This book is a proven tutorial for those new to C++, an authoritative discussion of core C++ concepts and techniques, and a valuable resource for experienced programmers, especially those eager to see C++11 enhancements illuminated.",
                            ISBN = "978-0321714114",
                            ListPrice = 34.990000000000002,
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0,
                            Title = "C++ Primer"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Jon Duckett",
                            CategoryId = 5,
                            Description = "Creates HTML and CSS accessible for amateurs, students, and professionals, using full-color content.\r\n    Uses infographics and lifestyle photos to simplify and engage.\r\n    Has a unique format that lets you read chapters from start to finish or delve into areas of interest.\r\n\r\nThis instructional book is fun to read and refer to. It will make you wish other technical topics were that easy, appealing, and fascinating!",
                            ISBN = "978-1118008188",
                            ListPrice = 7.8700000000000001,
                            Price = 6.0,
                            Price100 = 2.0,
                            Price50 = 4.0,
                            Title = "HTML and CSS: Design and Build Websites"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Dr. Charles Russell",
                            CategoryId = 5,
                            Description = "Python for Everybody teaches programming and software development through data exploration. Python solves data challenges that spreadsheets can't.\r\n\r\n\r\n\r\nPython, a free programming language for Macintosh, Windows, and Linux, is simple and quick to learn. Once you understand Python, you can use it throughout your career without buying software.",
                            ISBN = "978-1530051120",
                            ListPrice = 12.18,
                            Price = 5.0,
                            Price100 = 1.0,
                            Price50 = 2.0,
                            Title = "Python for Everybody: Exploring Data in Python 3"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Thomas H. Cormen",
                            CategoryId = 5,
                            Description = "Algorithm books might be rigorous yet incomplete or superficial but comprehensive. Introduction to Algorithms is uncommonly rigorous and detailed. It covers a wide range of algorithms in depth yet makes their construction and analysis easy for all readers with self-contained chapters and pseudocode algorithms. Introduction to Algorithms has been the top algorithms text in colleges and the standard reference for professionals since its initial edition. Updated throughout, this fourth edition.",
                            ISBN = "978-0262046305",
                            ListPrice = 93.579999999999998,
                            Price = 80.0,
                            Price100 = 50.0,
                            Price50 = 65.0,
                            Title = "Introduction to Algorithms, fourth edition 4th Edition"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Joshua Bloch",
                            CategoryId = 5,
                            Description = "The last version of Effective Java was published immediately after Java 6. Java has evolved substantially. This Jolt award-winning classic has been fully updated to use the newest language and library capabilities. Modern Java supports numerous paradigms, necessitating best practices guidance, which this book provides.\r\n\r\n\r\nAgain, each chapter of Effective Java, Third Edition has multiple “items,” each a brief, stand-alone article that offers guidance, Java platform insights, and updated code examples. What to do, what not to do, and why are explained in detail for each item.",
                            ISBN = "978-0134685991",
                            ListPrice = 38.079999999999998,
                            Price = 25.0,
                            Price100 = 10.0,
                            Price50 = 20.0,
                            Title = "Effective Java 3rd Edition"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Ben Forta",
                            CategoryId = 5,
                            Description = "SQL skills are essential for application developers, database administrators, online application designers, mobile app developers, and Microsoft Office users. Sams Teach Yourself SQL in 10 Minutes provides simple, practical solutions to help you accomplish your job.\r\n\r\nBen Forta, a famous trainer and author, starts with simple data retrieval and soon moves on to joins, subqueries, stored procedures, cursors, triggers, and table constraints. \r\n",
                            ISBN = "978-0135182796",
                            ListPrice = 20.0,
                            Price = 18.0,
                            Price100 = 9.0,
                            Price50 = 15.0,
                            Title = "SQL in 10 Minutes a Day, Sams Teach Yourself 5th Edition"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Jon Duckett",
                            CategoryId = 5,
                            Description = "In JavaScript & jQuery, famous author Jon Duckett breaks the programming book mold and makes coding more engaging. His full-color books with educational visuals and images have won over readers by explaining programming in a way that's easy for beginners and useful for experts.\r\n\r\nDuckett combines JavaScript and jQuery in one book to help you write functioning programs rapidly. But the book doesn't presume you know JavaScript or jQuery. Duckett uses popular jQuery plugins to demonstrate concepts that would take pages of comprehensive explanation if you were asked to design them. This robust and elegant hardback version will be a desk reference for years.",
                            ISBN = "978-1118531648",
                            ListPrice = 45.0,
                            Price = 30.0,
                            Price100 = 15.0,
                            Price50 = 20.0,
                            Title = "JavaScript and jQuery: Interactive Front-End Web Development 1st Edition"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Wouter de Bot",
                            CategoryId = 5,
                            Description = "\"ChatGPT: Transforming Your Life One Conversation at a Time\" is your complete guide to using AI for personal and professional advancement. This AI Empowerment Series book is a toolset for forward-thinking people eager to prosper in an AI-driven future.\r\nDon't miss \"AI Wealth Revolution: Unlocking the Earning Secrets\"—the second AI Empowerment Series book. Discover how AI can alter wealth production.\r\nStart your life-changing adventure with \"ChatGPT: Transforming Your Life One Conversation at a Time\". Get your copy today to improve your future.",
                            ISBN = "978-1118531648",
                            ListPrice = 12.0,
                            Price = 10.0,
                            Price100 = 2.0,
                            Price50 = 6.0,
                            Title = "ChatGPT"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Vivek Shetty",
                            CategoryId = 5,
                            Description = "* Hardcore .NET solutions for advanced, distributed financial applications.\r\n\r\n* Fascinating insight into operation of Equity markets and the challenges this poses for technology solutions – you do not have to be an equity market insider to use this book.\r\n\r\n* Examines next generation trading challenges, and potential solutions using .NET 2.0 and emerging technology, such as Avalon, Indigo and Longhorn. ",
                            ISBN = "978-1118531648",
                            ListPrice = 79.989999999999995,
                            Price = 50.0,
                            Price100 = 32.0,
                            Price50 = 41.0,
                            Title = "Practical .NET for Financial Markets (Expert's Voice in .NET) 1st ed. Edition"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Titus Winter & Tom Manshreck & Hyrum Wirght",
                            CategoryId = 5,
                            Description = "Software developers nowadays must know how to program well and build good engineering practices to keep their codebase healthy. This book focuses what distinguishes programming from software engineering.\r\nHow can software developers manage a live codebase that adapts to new needs? Software engineers Titus Winters and Hyrum Wright, along with technical writer Tom Manshreck, offer an honest and enlightening look at how some of the world's top software engineers build and maintain software based on their Google experience. Google's engineering culture, procedures, and tools and how they improve engineering organizations are covered in this book.",
                            ISBN = "979-8861298315 ",
                            ListPrice = 21.0,
                            Price = 18.0,
                            Price100 = 9.0,
                            Price50 = 15.0,
                            Title = "Software Engineering at Google"
                        });
                });

            modelBuilder.Entity("Bulky.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Bulky.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bulky.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Bulky.Models.OrderDetail", b =>
                {
                    b.HasOne("Bulky.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bulky.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bulky.Models.OrderHeader", b =>
                {
                    b.HasOne("Bulky.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bulky.Models.ProductImage", b =>
                {
                    b.HasOne("Bulky.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bulky.Models.ShoppingCart", b =>
                {
                    b.HasOne("Bulky.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bulky.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bulky.Models.ApplicationUser", b =>
                {
                    b.HasOne("Bulky.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
